### ISSUE TITLE
missing module error message when running test

### ISSUE THREAD

**Issue by Nic-Sevic** [learn-co-curriculum/for-each-lab#12]
Cloning lesson...
Opening lesson...
Installing npm dependencies...
yarn install v1.13.0
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is adv
ised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock fil
es. To clear this warning, remove package-lock.json.
[1/5] Validating package.json...
error for-each-lab@0.1.0: The engine "node" is incompatible with this module. Expected version "6.x". Got "8.15
.1"
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[10:04:30] (master) for-each-lab-js-intro-000
// ♥ learn test
added 124 packages from 470 contributors and audited 180 packages in 3.167s
found 4 vulnerabilities (2 low, 1 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
> for-each-lab@0.1.0 test /home/droll-course-8088/for-each-lab-js-intro-000
> mocha -R mocha-multi --reporter-options nyan=-,json=.results.json
 0   __,------,
 1   __|  /\_/\
 0   _~|_( x .x)
     _ ""  ""
0 passing (12ms)
  1 failing
  1)  "before all" hook:
     Error: Cannot find module 'jsdom/lib/old-api'
      at require (internal/module.js:11:18)
      at Context.<anonymous> (node_modules/mocha-jsdom/index.js:53:5)

**Comment by micahshute** [comment]
__Fix to above problem__ 

Change package.json`mocha` and `mocha-jsdom` versions to the following:

"mocha": "^2.5.3",
"mocha-jsdom": "~1.1.0"

And then run `npm install`
