### ISSUE TITLE
Redundant readme

### ISSUE THREAD

**Issue by ejf89** [learn-co-curriculum/for-each-lab#8]
The sentence below appears twice in the readme of this lab:

"Remember, you can run the tests using mocha.run() in the browser if you'd like — then read the results, refresh the page, and keep going afterwards.
You can run the tests using mocha.run() in the browser if you'd like — then read the results, refresh the page, and keep going afterwards."

**Comment by gj** [comment]
Fixed with #9.

Thanks!
